### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by juliohm** [SeismicJulia/Seismic.jl#63]
>With the update to julia version 1.0 and the new Pkg system, this package is inactive. You can still download and use this package, but consider instead using the new packages with updated modules

I have no idea of what are these new packages. Could you please share what is the current state of affairs in SeismicJulia? What is the package that new users should try in Julia v1.0 and beyond? Is there a package for segy IO?

**Comment by fercarozzi** [comment]
Hi juliohm, 
SeismicJulia got split into different packages. In this way, the user doesn't need to load the full library and the project is more approachable. 
Functions for SEGY IO are in SeisMain. This would be your entry point to the project. 
The exported functions when you load SeisMain are SegyToSeis, SeisRead, SeisReadHeaders, SeisWrite, SeisWriteHeaders, SeisCopy, SeisHeaderInfo, SeisToSegy, SeisRemove. These functions allow you to convert to SeismicJulia internal format, read, write, etc. 
SeisProcessing has all the modelling (SeisLinearEvents, SeisParabEvents, etc) and processing tools (SeisFXDecon, SeisNMO, SeisRadon, SeisStack, etc). 
SeisReconstruction includes reconstruction capabilities as MWNI, POCS and SpitzFX. 
SeisImaging has migration functions based on WEM, EWEM, LSWEM, and PostStack WEM. 
SeisAcoustics is a library for wave equation propagation modelling and imaging via FD. 
Finally, SeisPlot includes plotting capabilities. 
We hope you find the new SeismicJulia project enjoyable. Cheers.

**Comment by juliohm** [comment]
I still think the README needs some work. This information you are sharing here is not available there and users may just avoid the package because they don't know what is the state of affairs. Closing the issue after a long period with it open.
